version: "3.3"
services:
  api:
    container_name: "api"
    image: alpapago77/geoparty-api:latest
    build:
      context: .
      dockerfile: Dockerfile.api
    env_file: .env
    environment:
      - PORT=3000
      - SERVER_PORT=3000
    expose:
      - "3000"
    volumes:
      - ./docker/api/logs:/app/api/logs
      - ./docker/api/ormlogs.log:/app/api/ormlogs.log
  nginx:
    container_name: "nginx"
    image: alpapago77/geoparty-nginx:latest
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api
    volumes:
      - ./docker/nginx/nginx.conf:/home/ubuntu/geoparty/nginx.conf:ro
      - ./docker/nginx/logs:/app/nginx/logs
      - ./ssl:/etc/nginx/ssl:ro
