name: Deploy to EC2

on:
  push:
    branches: [ "main" ]  # main 브랜치에 push될 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push API
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.api
          push: true
          tags: alpapago77/geoparty-server-api:latest
          
      - name: Build and push Nginx
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.nginx
          push: true
          tags: alpapago77/geoparty-server-nginx:latest
          
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/geoparty
            docker-compose down
            docker pull alpapago77/geoparty-server-api:latest
            docker pull alpapago77/geoparty-server-nginx:latest
            docker-compose up -d
